# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.2.16-202602210227"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.16-202602210227/spark-cli_darwin_amd64.tar.gz"
      sha256 "17372fe558f5d95c57e7526cce8df5e2e48e934c264a35fa6ff42098ec599abd"

      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.16-202602210227/spark-cli_darwin_arm64.tar.gz"
      sha256 "e4e39e7d4729c6014631c8c83c5b8dc6eddc340abbbe25f392d1aa4770159c2b"

      def install
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.16-202602210227/spark-cli_linux_amd64.tar.gz"
      sha256 "7ce9af99fb9fb7acc12c93b4844e730007d0f2102fab6938c35f557cfdb96dc4"
      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.16-202602210227/spark-cli_linux_arm64.tar.gz"
      sha256 "d278cca85faa20145e1c109fe42f72536a7a7dcfb88d639715e45e1086cc33da"
      def install
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
