# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.2.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.28/spark-cli_darwin_amd64.tar.gz"
      sha256 "0baae0b2bd7cb9c94bef0b2ae128a1a6ba5d2be7137ed25f7c7cbcf5ebf285a2"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.28/spark-cli_darwin_arm64.tar.gz"
      sha256 "1710174b748ae7640cfc933c054ccd49e3877ad220cde14ee250296b79d5489f"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.28/spark-cli_linux_amd64.tar.gz"
      sha256 "2571ccb60324a8e270f2396e0291d62bcbe29a57657e433bda65744237b3e840"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.28/spark-cli_linux_arm64.tar.gz"
      sha256 "eff3152853dea301374e2a40f10f0a45ce864a7f7d83d9e494f25c6f28be3228"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
