# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.12/spk_darwin_amd64.tar.gz"
      sha256 "2a579a6dafaadcae5e2440786184a5a391a1f766f2ce298f730023aa0309006a"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.12/spk_darwin_arm64.tar.gz"
      sha256 "4fe933704f498832ee3bfb7ead449cc991ce6c808b815eaa0b10240febd4922a"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.12/spk_linux_amd64.tar.gz"
      sha256 "8e2abcd4685d26ccb21dd75b1f2e46bae27297d4d8d6cc23e0e9e1687ea934e0"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.12/spk_linux_arm64.tar.gz"
      sha256 "18701a3f2a6dc78a3ee7ae632d6abe59cf9c0244d416122b28560ab39c6cf147"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
